version: "3.9"

services:
  mariadb:
    image: mariadb:10.11
    container_name: fitflow-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: fitflow_db
      MARIADB_USER: fitflow
      MARIADB_PASSWORD: fitpass
    ports:
      - "3307:3306"         # host:container
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 20

  phpmyadmin:
    image: phpmyadmin:5.2
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: fitflow
      PMA_PASSWORD: fitpass
    ports:
      - "8082:80"

volumes:
  mariadb_data:
